import { useEffect, useState } from "react";
import Navbar from "../Navbar";
import Users from "../Users";
import "./index.css";

const users = [
    {
        name: "Renjith Kumar",
        email: "renjith.kumar@example.com",
        number: "9876543210",
        dob: "1990-01-15",
        country: "India",
        state: "Kerala",
        city: "Kochi",
        photo: "https://randomuser.me/api/portraits/men/1.jpg",
        role: "Front-end Developer",
        about: "Passionate about crafting user interfaces that are both beautiful and functional.",
        location: "Kochi, Kerala, India, 682001",
        skills: "HTML, CSS, JavaScript, React",
    },
    {
        name: "Devin Patel",
        email: "devin.patel@example.com",
        number: "9876543211",
        dob: "1988-05-20",
        country: "India",
        state: "Gujarat",
        city: "Ahmedabad",
        photo: "https://randomuser.me/api/portraits/men/2.jpg",
        role: "Software Engineer",
        about: "Enthusiastic coder with a knack for solving complex problems and optimizing performance.",
        location: "Ahmedabad, Gujarat, India, 380001",
        skills: "Java, Python, C++, Algorithms",
    },
    {
        name: "Kiran Sharma",
        email: "kiran.sharma@example.com",
        number: "9876543212",
        dob: "1992-11-10",
        country: "India",
        state: "Maharashtra",
        city: "Mumbai",
        photo: "https://randomuser.me/api/portraits/women/3.jpg",
        role: "UI/UX Designer",
        about: "Dedicated designer focused on creating intuitive and visually appealing user experiences.",
        location: "Mumbai, Maharashtra, India, 400001",
        skills: "Sketch, Figma, Adobe XD, User Research",
    },
    {
        name: "Priya Gupta",
        email: "priya.gupta@example.com",
        number: "9876543213",
        dob: "1995-03-25",
        country: "India",
        state: "Uttar Pradesh",
        city: "Lucknow",
        photo: "https://randomuser.me/api/portraits/women/4.jpg",
        role: "Product Manager",
        about: "Strategic thinker passionate about launching products that solve real-world problems.",
        location: "Lucknow, Uttar Pradesh, India, 226001",
        skills: "Product Roadmapping, Market Research, Agile, Jira",
    },
    {
        name: "Rahul Singh",
        email: "rahul.singh@example.com",
        number: "9876543214",
        dob: "1985-09-08",
        country: "India",
        state: "Delhi",
        city: "New Delhi",
        photo: "https://randomuser.me/api/portraits/men/5.jpg",
        role: "Backend Developer",
        about: "Experienced developer specializing in building scalable and secure server-side applications.",
        location: "New Delhi, Delhi, India, 110001",
        skills: "Node.js, Express.js, MongoDB, SQL",
    },
    {
        name: "Neha Verma",
        email: "neha.verma@example.com",
        number: "9876543215",
        dob: "1991-07-12",
        country: "India",
        state: "Rajasthan",
        city: "Jaipur",
        photo: "https://randomuser.me/api/portraits/women/6.jpg",
        role: "Data Scientist",
        about: "Data enthusiast skilled in analyzing complex datasets and extracting meaningful insights.",
        location: "Jaipur, Rajasthan, India, 302001",
        skills: "Python, R, Machine Learning, Data Visualization",
    },
    {
        name: "Sandeep Reddy",
        email: "sandeep.reddy@example.com",
        number: "9876543216",
        dob: "1987-04-18",
        country: "India",
        state: "Telangana",
        city: "Hyderabad",
        photo: "https://randomuser.me/api/portraits/men/7.jpg",
        role: "DevOps Engineer",
        about: "Expert in automating deployment pipelines and ensuring continuous integration.",
        location: "Hyderabad, Telangana, India, 500001",
        skills: "CI/CD, Jenkins, Docker, Kubernetes",
    },
    {
        name: "Shreya Desai",
        email: "shreya.desai@example.com",
        number: "9876543217",
        dob: "1993-12-30",
        country: "India",
        state: "Karnataka",
        city: "Bangalore",
        photo: "https://randomuser.me/api/portraits/women/8.jpg",
        role: "QA Engineer",
        about: "Detail-oriented tester dedicated to ensuring software quality through rigorous testing.",
        location: "Bangalore, Karnataka, India, 560001",
        skills: "Selenium, JUnit, Test Automation, Manual Testing",
    },
    {
        name: "Ajay Kumar",
        email: "ajay.kumar@example.com",
        number: "9876543218",
        dob: "1989-06-05",
        country: "India",
        state: "Tamil Nadu",
        city: "Chennai",
        photo: "https://randomuser.me/api/portraits/men/9.jpg",
        role: "System Administrator",
        about: "IT professional experienced in maintaining and securing enterprise IT infrastructures.",
        location: "Chennai, Tamil Nadu, India, 600001",
        skills: "Linux, Windows Server, Network Security, Virtualization",
    },
    {
        name: "Pooja Mehta",
        email: "pooja.mehta@example.com",
        number: "9876543219",
        dob: "1990-08-22",
        country: "India",
        state: "Punjab",
        city: "Chandigarh",
        photo: "https://randomuser.me/api/portraits/women/10.jpg",
        role: "Technical Writer",
        about: "Passionate writer dedicated to creating clear and concise technical documentation.",
        location: "Chandigarh, Punjab, India, 160001",
        skills: "Technical Writing, Documentation, Content Creation, MS Word",
    },
    {
        name: "Ravi Kumar",
        email: "ravi.kumar@example.com",
        number: "9876543220",
        dob: "1986-11-05",
        country: "India",
        state: "Bihar",
        city: "Patna",
        photo: "https://randomuser.me/api/portraits/men/11.jpg",
        role: "Network Engineer",
        about: "Networking professional skilled in designing and managing enterprise network infrastructures.",
        location: "Patna, Bihar, India, 800001",
        skills: "Cisco, Network Design, Firewalls, Troubleshooting",
    },
    {
        name: "Anjali Joshi",
        email: "anjali.joshi@example.com",
        number: "9876543221",
        dob: "1992-02-14",
        country: "India",
        state: "Madhya Pradesh",
        city: "Bhopal",
        photo: "https://randomuser.me/api/portraits/women/12.jpg",
        role: "UX Designer",
        about: "Creative designer passionate about crafting intuitive and user-friendly digital experiences.",
        location: "Bhopal, Madhya Pradesh, India, 462001",
        skills: "Sketch, Figma, Prototyping, User Research",
    },
    {
        name: "Vikram Singh",
        email: "vikram.singh@example.com",
        number: "9876543222",
        dob: "1984-03-28",
        country: "India",
        state: "Haryana",
        city: "Chandigarh",
        photo: "https://randomuser.me/api/portraits/men/13.jpg",
        role: "Business Analyst",
        about: "Analytical thinker adept at analyzing market trends and driving business growth.",
        location: "Chandigarh, Haryana, India, 160001",
        skills: "Data Analysis, Market Research, SQL, Excel",
    },
    {
        name: "Smita Sharma",
        email: "smita.sharma@example.com",
        number: "9876543223",
        dob: "1994-09-17",
        country: "India",
        state: "West Bengal",
        city: "Kolkata",
        photo: "https://randomuser.me/api/portraits/women/14.jpg",
        role: "Marketing Manager",
        about: "Creative marketing professional focused on driving brand awareness and engagement.",
        location: "Kolkata, West Bengal, India, 700001",
        skills: "Digital Marketing, SEO, Social Media, Campaign Management",
    },
    {
        name: "Amit Patel",
        email: "amit.patel@example.com",
        number: "9876543224",
        dob: "1991-12-09",
        country: "India",
        state: "Andhra Pradesh",
        city: "Vijayawada",
        photo: "https://randomuser.me/api/portraits/men/15.jpg",
        role: "Database Administrator",
        about: "DBA with extensive experience in managing and optimizing relational databases.",
        location: "Vijayawada, Andhra Pradesh, India, 520001",
        skills: "SQL, Oracle, Database Design, Performance Tuning",
    },
    {
        name: "Ritu Kapoor",
        email: "ritu.kapoor@example.com",
        number: "9876543225",
        dob: "1987-07-05",
        country: "India",
        state: "Himachal Pradesh",
        city: "Shimla",
        photo: "https://randomuser.me/api/portraits/women/16.jpg",
        role: "HR Manager",
        about: "HR professional committed to building a positive and productive workplace culture.",
        location: "Shimla, Himachal Pradesh, India, 171001",
        skills: "Recruitment, Employee Relations, Payroll, HR Policies",
    },
];

function Dashboard() {
    const [usersData, setUsersData] = useState([]);

    useEffect(() => {
        const data = JSON.parse(localStorage.getItem("userdata")) || users;
        setUsersData(data);
    }, []);

    return (
        <div className="app">
            <Navbar />
            <Users userData={usersData} />
        </div>
    );
}

export default Dashboard;
